[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["radicalpanda"]
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.115.5",
    "openai==1.54.4",
    "uvicorn==0.32.0",
    "duckduckgo-search>=6.2",
    "fastdownload>=0.0.7",
    "python-dotenv>=1.0.0",
    "pydantic>=2.9.2",
]
