REFLECTION_PROMPTS = [
    "What symbols in this card draw your attention?",
    "What emotions does this card stir within you?",
    "What story does this card tell you?",
    "What hidden messages do you see in the imagery?",
    "What energies do you feel emanating from this card?",
    "What details in this card speak directly to you?",
    "What deeper meaning reveals itself to you?",
    "What wisdom does this card hold for your situation?",
    "What patterns or symbols catch your eye?",
    "What aspects of your life does this card illuminate?",
    "How does this imagery connect to your inner journey?",
    "What memories or thoughts surface as you gaze at this card?",
    "What metaphors in this card resonate with your path?",
    "How does this card mirror your current experience?",
    "What secrets does this card whisper to your soul?",
    "How does this image reflect your deepest questions?",
    "What personal truth emerges from these symbols?",
    "How does this card speak to your present moment?",
    "What unconscious wisdom does this card reveal?",
    "How does this imagery dance with your intuition?",
    "What hidden aspects of yourself do you see reflected?",
    "How does this card challenge your perspective?",
    "What deeper understanding awaits in these symbols?",
    "How does this card illuminate your path forward?",
    "What unspoken message does this card hold for you?",
    "How does this imagery touch your inner knowing?",
    "What personal significance emerges from this card?",
    "How does this card reflect your spiritual journey?",
    "What subtle energies do you sense in this image?",
    "What transformative message lies within this card?"
]